services:
  plucklog_mongo:
    image: mongo:latest
    container_name: plucklog_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: plucklog_db

  plucklog_fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plucklog_fastapi
    restart: always
    depends_on:
      - plucklog_mongo
    environment:
      - MONGO_URI=mongodb://plucklog_mongo:27017
      - MONGO_DB=plucklog_db
      - CORS_ALLOW_ORIGINS=http://localhost,http://localhost:3000,http://localhost:80
    ports:
      - "8000:8000"

  plucklog_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: plucklog_frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api
    ports:
      - "3000:3000"

  plucklog_nginx:
    image: nginx:alpine
    container_name: plucklog_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - plucklog_fastapi
      - plucklog_frontend

volumes:
  mongo_data:
