services:
  - type: web
    name: plucklog
    env: docker
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: plucklog_db
      - key: SECRET_KEY
        generateValue: true
      - key: PLUCKLOG_FASTAPI_HOSTPORT
        value: 127.0.0.1:8000
