services:
  - type: web
    name: pluckhub
    env: docker
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: almox_sms
      - key: SECRET_KEY
        generateValue: true
